"""Local synthetic interaction console for the research API."""

CONSOLE_HTML = """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reflection AI research console</title><style>body{font:16px system-ui;max-width:900px;margin:2rem auto;padding:0 1rem;color:#17212b}input,textarea,button{font:inherit}input,textarea{box-sizing:border-box;width:100%;padding:.6rem}textarea{min-height:7rem}button{padding:.7rem 1rem;margin:.8rem .5rem 0 0}label{display:block;font-weight:600;margin-top:1rem}pre{background:#f2f4f7;padding:1rem;overflow:auto}.warn{border-left:4px solid #a23b24;background:#fff1ec;padding:.8rem}</style></head><body><h1>Reflection AI research console</h1>
<p class="warn">Synthetic local research only. Authentication and tenant isolation are not implemented. Never enter real personal, patient, credential, or confidential data.</p>
<label for="external">Synthetic subject ID</label><input id="external" value="synthetic-browser-subject"><button id="create">Create consented synthetic subject</button><button id="capabilities">Capabilities</button>
<label for="preference">Synthetic preference or correction</label><textarea id="preference">I prefer concise explanations with a short example.</textarea><button id="add" disabled>Add preference event</button><button id="remove" disabled>Delete synthetic subject</button><pre id="result" aria-live="polite">No subject created.</pre>
<script>let user=null;const out=document.querySelector('#result');const show=async response=>{const body=response.status===204?{deleted:true}:await response.json();out.textContent=JSON.stringify({status:response.status,...body},null,2);return body};
document.querySelector('#create').onclick=async()=>{try{const response=await fetch('/v1/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({external_id:document.querySelector('#external').value+'-'+Date.now(),application_id:'local-console',tenant_id:'synthetic-only',consent:true,training_consent:false,attributes:{learning_enabled:true}})});const body=await show(response);if(response.ok){user=body;document.querySelector('#add').disabled=false;document.querySelector('#remove').disabled=false}}catch(error){out.textContent=String(error)}};
document.querySelector('#add').onclick=async()=>{if(!user)return;try{await show(await fetch(`/v1/users/${user.id}/events`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'preference',input_text:document.querySelector('#preference').value,source:'local-console',idempotency_key:'browser-'+Date.now()})}))}catch(error){out.textContent=String(error)}};
document.querySelector('#remove').onclick=async()=>{if(!user)return;try{await show(await fetch(`/v1/users/${user.id}`,{method:'DELETE'}));user=null;document.querySelector('#add').disabled=true;document.querySelector('#remove').disabled=true}catch(error){out.textContent=String(error)}};
document.querySelector('#capabilities').onclick=async()=>{try{await show(await fetch('/v1/capabilities'))}catch(error){out.textContent=String(error)}};</script></body></html>"""
